### ISSUE TITLE
Parsing of title stops at '.' and throws away the rest

### ISSUE THREAD

**Issue by erikoui** [antoniouaa/krypto#52]
How to reproduce:

```
//TODO: ensure foo.bar works.
// body here
```

will open an issue with title `ensure foo` and body `body here`

Desired behaviour: Title should be `ensure foo.bar works.`

**Comment by antoniouaa** [comment]
Ela, the problem is with the regex in [todo.py](https://github.com/antoniouaa/krypto/blob/master/krypto/todo.py#L9).

I'm gonna add the literal `.` in there but if you wanna do some refactoring, be my guest, regex sucks anyway.
Right now the only things captured are `([\d\w\s\-\.]*)`

**Comment by antoniouaa** [comment]
Changing the regex above to `.*` passes all test cases so im just gonna do that instead.
